const apiResponse = ''' 
[
  {
    "createdAt": "2021-08-12T04:22:51.701Z",
    "name": "Gloves",
    "color": "silver",
    "price": "527.00",
    "discount": 66,
    "rating": 96,
    "favorite": true,
    "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Games",
    "sizes": "sizes 1",
    "payments": "payments 1",
    "id": "1"
  },
  {
    "createdAt": "2021-08-12T06:07:23.250Z",
    "name": "Shoes",
    "color": "lime",
    "price": "250.00",
    "discount": 38,
    "rating": 11,
    "favorite": true,
    "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Shoes",
    "sizes": "sizes 2",
    "payments": "payments 2",
    "id": "2"
  },
  {
    "createdAt": "2021-08-12T01:16:58.770Z",
    "name": "Chair",
    "color": "pink",
    "price": "947.00",
    "discount": 7,
    "rating": 95,
    "favorite": false,
    "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Electronics",
    "sizes": "sizes 3",
    "payments": "payments 3",
    "id": "3"
  },
  {
    "createdAt": "2021-08-11T16:50:05.029Z",
    "name": "Cheese",
    "color": "purple",
    "price": "367.00",
    "discount": 26,
    "rating": 26,
    "favorite": true,
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Baby",
    "sizes": "sizes 4",
    "payments": "payments 4",
    "id": "4"
  },
  {
    "createdAt": "2021-08-12T08:48:20.802Z",
    "name": "Chicken",
    "color": "lavender",
    "price": "491.00",
    "discount": 15,
    "rating": 25,
    "favorite": false,
    "description": "The Football Is Good For Training And Recreational Purposes",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Baby",
    "sizes": "sizes 5",
    "payments": "payments 5",
    "id": "5"
  },
  {
    "createdAt": "2021-08-11T22:44:52.329Z",
    "name": "Chicken",
    "color": "yellow",
    "price": "436.00",
    "discount": 53,
    "rating": 51,
    "favorite": true,
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Music",
    "sizes": "sizes 6",
    "payments": "payments 6",
    "id": "6"
  },
  {
    "createdAt": "2021-08-12T12:13:55.556Z",
    "name": "Soap",
    "color": "white",
    "price": "314.00",
    "discount": 34,
    "rating": 33,
    "favorite": true,
    "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Grocery",
    "sizes": "sizes 7",
    "payments": "payments 7",
    "id": "7"
  },
  {
    "createdAt": "2021-08-12T04:38:33.200Z",
    "name": "Pants",
    "color": "purple",
    "price": "717.00",
    "discount": 56,
    "rating": 35,
    "favorite": true,
    "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Toys",
    "sizes": "sizes 8",
    "payments": "payments 8",
    "id": "8"
  },
  {
    "createdAt": "2021-08-12T01:13:54.045Z",
    "name": "Chips",
    "color": "mint green",
    "price": "504.00",
    "discount": 56,
    "rating": 9,
    "favorite": true,
    "description": "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Computers",
    "sizes": "sizes 9",
    "payments": "payments 9",
    "id": "9"
  },
  {
    "createdAt": "2021-08-12T04:53:33.865Z",
    "name": "Shirt",
    "color": "purple",
    "price": "373.00",
    "discount": 74,
    "rating": 45,
    "favorite": true,
    "description": "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Games",
    "sizes": "sizes 10",
    "payments": "payments 10",
    "id": "10"
  }
]
''';