const apiResponse = ''' 
[
  {
    "createdAt": "2021-08-13T07:32:55.078Z",
    "name": "Towels",
    "color": "olive",
    "price": "536.00",
    "discount": 11,
    "rating": 70,
    "favorite": true,
    "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Tools",
    "sizes": "sizes 1",
    "payments": "payments 1",
    "freeDelivery": false,
    "id": "1"
  },
  {
    "createdAt": "2021-08-12T20:43:46.574Z",
    "name": "Sausages",
    "color": "gold",
    "price": "173.00",
    "discount": 60,
    "rating": 55,
    "favorite": false,
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Computers",
    "sizes": "sizes 2",
    "payments": "payments 2",
    "freeDelivery": false,
    "id": "2"
  },
  {
    "createdAt": "2021-08-13T06:08:55.861Z",
    "name": "Sausages",
    "color": "sky blue",
    "price": "266.00",
    "discount": 32,
    "rating": 58,
    "favorite": false,
    "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Electronics",
    "sizes": "sizes 3",
    "payments": "payments 3",
    "freeDelivery": true,
    "id": "3"
  },
  {
    "createdAt": "2021-08-12T23:34:10.574Z",
    "name": "Towels",
    "color": "mint green",
    "price": "505.00",
    "discount": 18,
    "rating": 9,
    "favorite": false,
    "description": "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Music",
    "sizes": "sizes 4",
    "payments": "payments 4",
    "freeDelivery": true,
    "id": "4"
  },
  {
    "createdAt": "2021-08-13T02:51:54.743Z",
    "name": "Bacon",
    "color": "tan",
    "price": "653.00",
    "discount": 25,
    "rating": 2,
    "favorite": false,
    "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Electronics",
    "sizes": "sizes 5",
    "payments": "payments 5",
    "freeDelivery": false,
    "id": "5"
  },
  {
    "createdAt": "2021-08-13T12:49:43.241Z",
    "name": "Chips",
    "color": "violet",
    "price": "134.00",
    "discount": 18,
    "rating": 46,
    "favorite": true,
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Automotive",
    "sizes": "sizes 6",
    "payments": "payments 6",
    "freeDelivery": true,
    "id": "6"
  },
  {
    "createdAt": "2021-08-13T07:05:32.515Z",
    "name": "Shirt",
    "color": "azure",
    "price": "226.00",
    "discount": 87,
    "rating": 17,
    "favorite": false,
    "description": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Baby",
    "sizes": "sizes 7",
    "payments": "payments 7",
    "freeDelivery": false,
    "id": "7"
  },
  {
    "createdAt": "2021-08-13T01:55:10.311Z",
    "name": "Car",
    "color": "purple",
    "price": "468.00",
    "discount": 26,
    "rating": 27,
    "favorite": false,
    "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Clothing",
    "sizes": "sizes 8",
    "payments": "payments 8",
    "freeDelivery": true,
    "id": "8"
  },
  {
    "createdAt": "2021-08-13T04:49:54.696Z",
    "name": "Shirt",
    "color": "red",
    "price": "551.00",
    "discount": 66,
    "rating": 29,
    "favorite": false,
    "description": "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Books",
    "sizes": "sizes 9",
    "payments": "payments 9",
    "freeDelivery": true,
    "id": "9"
  },
  {
    "createdAt": "2021-08-13T11:42:51.150Z",
    "name": "Fish",
    "color": "green",
    "price": "800.00",
    "discount": 66,
    "rating": 27,
    "favorite": true,
    "description": "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
    "image": "http://placeimg.com/640/480/fashion",
    "department": "Sports",
    "sizes": "sizes 10",
    "payments": "payments 10",
    "freeDelivery": false,
    "id": "10"
  }
]
''';